#!/usr/bin/env python3
"""
Embed configuration into the app bundle.
Put your values in secrets.env, then: python3 embed_credentials.py
Then run build_mac_dmg.sh. Do not commit secrets.env or _bundled_secrets.py.

ENV_KEYS: env keys used in config.py, app_simple.py, adoptiq_backend.py,
cisco_integration_config.py, cisco_internal_integrations.py, enhanced_admin_dashboard_v2.py, setup.py.
"""
import base64
from pathlib import Path

# Env keys used in the codebase (config.py, app_simple.py, adoptiq_backend, etc.).
# Path/timeout keys (OUTPUT_FOLDER, UPLOAD_FOLDER, etc.) are not embedded; frozen app uses Application Support.
ENV_KEYS = [
    "ADOPTIQ_MAIN_URL",      # enhanced_admin_dashboard_v2.py
    "CSONE_ONEDRIVE_FOLDER", # config.py - override OneDrive folder for CSOne reports
    "CSONE_SHARED_FOLDER_URL", # config.py - shared folder URL for "Open shared folder" button
    "ADOPTIQ_SECRET_KEY",    # config.py, app_simple.py
    "ADOPTIQ_ADMIN_SECRET_KEY",  # enhanced_admin_dashboard_v2.py (required for packaged builds)
    "ANTHROPIC_API_KEY",     # cisco_internal_integrations.py
    "BST_API_KEY",           # app_simple.py, cisco_integration_config.py
    "BST_CLIENT_SECRET",     # cisco_integration_config.py
    "BST_ENABLE_WEB_SCRAPING",  # cisco_internal_integrations.py
    "CIRCUIT_API_KEY",       # cisco_integration_config.py
    "CIRCUIT_APP_KEY",       # config.py
    "CIRCUIT_CLIENT_ID",     # config.py
    "CIRCUIT_CLIENT_SECRET", # config.py
    "CIRCUIT_MODEL_NAME",    # config.py
    "KEEPER_NAMESPACE",      # config.py
    "KEEPER_ROLE_ID",        # config.py
    "KEEPER_SECRET_ID",      # config.py
    "KEEPER_SECRET_PATH",    # config.py
    "KEEPER_URL",            # config.py
    "PSIRT_API_KEY",        # app_simple.py
    "PSIRT_CLIENT_SECRET",   # app_simple.py
    "SECRET_KEY",            # config.py
    "SNOWFLAKE_ACCOUNT",     # config.py, setup.py
    "SNOWFLAKE_DATABASE",    # setup.py
    "SNOWFLAKE_PASSWORD",    # config.py
    "SNOWFLAKE_ROLE",        # config.py
    "SNOWFLAKE_SCHEMA",      # setup.py
    "SNOWFLAKE_USER",        # config.py
    "SNOWFLAKE_WAREHOUSE",   # config.py
]

# Obfuscation key (same in script and generated module)
OBFUSCATE_KEY = "AdoptIQ-Mac-2024"


def _xor_bytes(data: bytes, key: str) -> bytes:
    kb = key.encode("utf-8")
    return bytes(b ^ kb[i % len(kb)] for i, b in enumerate(data))


def _encode_value(s: str) -> str:
    raw = _xor_bytes(s.encode("utf-8"), OBFUSCATE_KEY)
    return base64.b64encode(raw).decode("ascii")


def _decode_value(encoded: str) -> str:
    raw = base64.b64decode(encoded.encode("ascii"))
    return _xor_bytes(raw, OBFUSCATE_KEY).decode("utf-8")


def _parse_env_file(path: Path) -> dict:
    out = {}
    if not path.exists():
        return out
    with open(path, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            if "=" in line:
                k, _, v = line.partition("=")
                k = k.strip()
                v = v.strip().strip('"').strip("'")
                if k in ENV_KEYS and v:
                    out[k] = v
    return out


def main():
    root = Path(__file__).resolve().parent
    # Prefer secrets.env so .env can stay for local dev without embedding
    env_path = root / "secrets.env"
    if not env_path.exists():
        env_path = root / ".env"
    secrets = _parse_env_file(env_path)
    if not secrets:
        print("No secrets.env or .env found with values. Copy secrets.env.template to secrets.env, fill in values, then run again.")
        return 1

    # Generate _bundled_secrets.py (decoder + obfuscated data)
    lines = [
        "# Auto-generated by embed_credentials.py - do not edit.",
        "import base64",
        "",
        "_KEY = " + repr(OBFUSCATE_KEY),
        "_DATA = {",
    ]
    for k, v in sorted(secrets.items()):
        enc = _encode_value(v)
        lines.append(f'    {repr(k)}: {repr(enc)},')
    lines.append("}")
    lines.append("")
    lines.append("def _xor_bytes(data: bytes, key: str):")
    lines.append("    kb = key.encode(\"utf-8\")")
    lines.append("    return bytes(b ^ kb[i % len(kb)] for i, b in enumerate(data))")
    lines.append("")
    lines.append("def get_secrets():")
    lines.append("    out = {}")
    lines.append("    for k, enc in _DATA.items():")
    lines.append("        raw = base64.b64decode(enc.encode(\"ascii\"))")
    lines.append("        out[k] = _xor_bytes(raw, _KEY).decode(\"utf-8\")")
    lines.append("    return out")
    lines.append("")

    out_path = root / "_bundled_secrets.py"
    with open(out_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    print(f"Wrote {out_path} with {len(secrets)} obfuscated keys.")

    # Warn if Snowflake/Keeper credentials are missing (app will fail at runtime)
    has_snowflake = all(secrets.get(k) for k in ("SNOWFLAKE_USER", "SNOWFLAKE_ACCOUNT", "SNOWFLAKE_PASSWORD"))
    has_keeper = all(secrets.get(k) for k in ("KEEPER_ROLE_ID", "KEEPER_SECRET_ID"))
    if not has_snowflake and not has_keeper:
        print("WARNING: No Snowflake or Keeper credentials embedded. Add SNOWFLAKE_USER, SNOWFLAKE_ACCOUNT, SNOWFLAKE_PASSWORD (or KEEPER_ROLE_ID, KEEPER_SECRET_ID) to secrets.env and re-run to avoid runtime errors.")
    if not secrets.get("ADOPTIQ_SECRET_KEY"):
        print("WARNING: ADOPTIQ_SECRET_KEY is missing. Packaged builds will not start; add it to secrets.env and re-run embed_credentials.py.")
    if not secrets.get("ADOPTIQ_ADMIN_SECRET_KEY"):
        print("WARNING: ADOPTIQ_ADMIN_SECRET_KEY is missing. Packaged builds will not start; add it to secrets.env and re-run embed_credentials.py.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
