"""Round 73 / Phase 3 (F9): no MEDIUM in the Risk Score Methodology paragraph.

Pre-Round 73 the ``Risk Score Methodology (0-100 scale)`` paragraph
generated by ``report_utils._render_risk_scoring_explanation`` rendered
the band labels ``CRITICAL / HIGH / MEDIUM / LOW / HEALTHY``.  This was
the SINGLE remaining user-facing surface in the Renewal Word doc still
emitting ``MEDIUM`` -- the R67 / B1 + B6 remap covered the
``Risk_Level`` column on Compact / Renewal XLSX, the R70 / Phase 3 #11
remap covered the Top-N Focus Accounts table cell paint, the Risk
Score box, the donut gauge, and the panel-2 of the 2x2 portfolio
chart.  The R70 vocabulary lint
(``test_round70_no_medium_in_user_facing.py``) explicitly whitelisted
the methodology paragraph (its docstring noted "1 of 9 hits is in the
deliberate Risk Score Methodology paragraph; that single instance is
fine").

Build 46 audit found this remaining ``MEDIUM`` was inconsistent with
the rest of the document and confused operators who saw "MODERATE"
everywhere ELSE in the report.  R73 / F9 closes the gap by remapping
the band string to ``MODERATE`` in the methodology paragraph render
itself.

The internal ``RISK_BAND_THRESHOLDS`` dict KEY stays ``MEDIUM`` for
cross-sheet parity (Comprehensive ``Risk_Components.risk_band`` agrees
byte-for-byte) and so internal filter / color lookups still resolve
correctly -- only the rendered user-facing string is remapped.

This file pins the F9 fix at three layers:

* The methodology paragraph contains ``MODERATE`` (not ``MEDIUM``).
* The ``RISK_BAND_THRESHOLDS`` dict KEY is unchanged (canonical
  band key contract preserved).
* The R73 / F9 source marker is in place so a future revert fails
  this assertion.
"""

from __future__ import annotations

from pathlib import Path

import pytest

PROJECT_ROOT = Path(__file__).resolve().parent.parent


def _read_report_utils_source() -> str:
    return (PROJECT_ROOT / "report_utils.py").read_text(encoding="utf-8")


# ---------------------------------------------------------------------------
# Source-shape pin
# ---------------------------------------------------------------------------


def test_source_marker_for_r73_f9_is_present():
    body = _read_report_utils_source()
    assert "Round 73 / Phase 3 (F9)" in body, (
        "Round 73 / F9: source marker missing -- the MODERATE remap in "
        "the methodology paragraph may have been reverted"
    )


def test_methodology_band_paragraph_uses_moderate_not_medium():
    """The rendered ``bands`` f-string MUST emit ``MODERATE (...)`` and
    MUST NOT emit ``MEDIUM (...)`` (the parenthesised form used in the
    rendered text)."""

    body = _read_report_utils_source()
    # The new MODERATE rendering must be present.
    assert 'f"MODERATE ({_fmt(med)}-{_fmt(high - 1)}), "' in body, (
        "Round 73 / F9: methodology paragraph must render MODERATE "
        "(not MEDIUM) for the rendered band label string"
    )
    # The pre-R73 MEDIUM rendering must be gone.
    assert 'f"MEDIUM ({_fmt(med)}-{_fmt(high - 1)}), "' not in body, (
        "Round 73 / F9: methodology paragraph still renders the legacy "
        "MEDIUM band label string -- the rename is incomplete"
    )


def test_risk_band_thresholds_dict_key_remains_medium():
    """R67 / B6 contract preserved: the canonical ``RISK_BAND_THRESHOLDS``
    dict KEY stays ``MEDIUM`` so cross-sheet parity (Comprehensive
    ``Risk_Components.risk_band``) and internal filter / color lookups
    still resolve correctly."""

    body = _read_report_utils_source()
    # The dict-key access pattern must still use MEDIUM (canonical key).
    assert '_BANDS.get("MEDIUM"' in body, (
        "Round 73 / F9: methodology renderer must still read the "
        "MEDIUM threshold from RISK_BAND_THRESHOLDS via the canonical "
        "key (R67 / B6 contract -- only the RENDERED string was "
        "remapped, not the dict key)"
    )

    # And the canonical RISK_BAND_THRESHOLDS dict in canonical_metrics
    # MUST still carry MEDIUM as a key.
    cm_body = (PROJECT_ROOT / "canonical_metrics.py").read_text(encoding="utf-8")
    assert '"MEDIUM"' in cm_body or "'MEDIUM'" in cm_body, (
        "Round 73 / F9: RISK_BAND_THRESHOLDS dict in canonical_metrics "
        "must still carry MEDIUM as a key (canonical band key contract)"
    )


# ---------------------------------------------------------------------------
# Runtime pin
# ---------------------------------------------------------------------------


def test_get_risk_scoring_explanation_carries_moderate_not_medium():
    """Render the methodology paragraph at runtime and verify the
    user-facing band label string is MODERATE."""

    from report_utils import get_risk_scoring_explanation  # noqa: PLC0415

    text = get_risk_scoring_explanation()
    # The methodology paragraph carries the parenthesised form
    # ``MODERATE (35-54)`` (or whatever the threshold values are).
    # We only check the band label token + opening paren; the actual
    # numbers depend on RISK_BAND_THRESHOLDS so are not pinned here.
    assert "MODERATE (" in text, (
        f"Round 73 / F9: methodology paragraph missing 'MODERATE (' "
        f"band label; got:\n{text}"
    )
    # The legacy MEDIUM rendering must be absent from the rendered string.
    # Note: we test for the SPECIFIC parenthesised form 'MEDIUM (' to
    # avoid false positives if a comment / explanation mentions MEDIUM
    # in a non-band-label context (currently none, but defensive).
    assert "MEDIUM (" not in text, (
        f"Round 73 / F9: methodology paragraph still carries 'MEDIUM (' "
        f"band label; got:\n{text}"
    )


def test_methodology_paragraph_carries_full_user_facing_band_set():
    """Sanity: the methodology paragraph carries CRITICAL / HIGH /
    MODERATE / LOW / HEALTHY (the full user-facing band set)."""

    from report_utils import get_risk_scoring_explanation  # noqa: PLC0415

    text = get_risk_scoring_explanation()
    for band in ("CRITICAL", "HIGH", "MODERATE", "LOW", "HEALTHY"):
        assert f"{band} (" in text or f"{band} (>" in text or f"{band} (<" in text, (
            f"Round 73 / F9: methodology paragraph missing {band!r} band "
            f"label; got:\n{text}"
        )


# ---------------------------------------------------------------------------
# Regression pin: existing R67 / R70 user-facing remaps still in place.
# ---------------------------------------------------------------------------


def test_r67_b1_compact_risk_level_remap_still_present():
    """R67 / B1 contract preserved: the Compact ``Risk_Level`` column
    is still remapped at the row-build site so the artifact carries
    MODERATE (not MEDIUM)."""

    body = (PROJECT_ROOT / "app_simple.py").read_text(encoding="utf-8")
    assert "_r67_b6_LABEL_REMAP" in body, (
        "Round 73 / F9: R67 / B6 remap helper missing -- the F9 fix is "
        "complementary to (not a replacement for) the existing R67 / B1 "
        "+ B6 user-facing vocabulary remaps"
    )


def test_r70_top10_focus_remap_still_present():
    """R70 / Phase 3 #11 contract preserved: the Top-10 Focus Accounts
    table cell paint still goes through ``_r70_focus_LABEL_REMAP``."""

    body = (PROJECT_ROOT / "app_simple.py").read_text(encoding="utf-8")
    assert "_r70_focus_LABEL_REMAP" in body, (
        "Round 73 / F9: R70 Top-10 Focus Accounts remap helper missing "
        "-- the F9 fix complements (does not replace) the R70 remaps"
    )
