"""Round 75 / Phase 5 -- R74 enforcer first-run smoke test.

Build 47 acceptance audit confirmed the operator never installed the
Build 48 DMG that R74 baked, so the R74/P0
``_r74_footer_enforcer.enforce_build_label_footer`` post-save XML
enforcer has NEVER executed in production.  Build 49 ships the
enforcer first-run alongside the four R75 data fixes; this test
mints a synthetic empty-footer .docx (the exact shape every Build 47
production artifact has), runs the enforcer on it, re-opens the
.docx, and asserts ``word/footer1.xml`` carries the build-label
sentinel.

This catches any wiring regression in the enforcer (e.g. a future
change to ``_resolve_label`` that returns None silently, a zip
rewrite path that fails mid-flight, an idempotency check that
mis-fires) BEFORE the operator installs.  Without this test the only
way to know the enforcer works is to install Build 49 and open one
of the produced reports -- the same operator-trap loop Build 47
caught.

Round 75 / Phase 5.  Made-with: Cursor.
"""

from __future__ import annotations

import os
import shutil
import zipfile
from pathlib import Path
from tempfile import TemporaryDirectory

import pytest

# python-docx is the lightest way to produce a valid empty-footer .docx
# without manually constructing all the WordprocessingML parts.
docx = pytest.importorskip("docx")

from _r74_footer_enforcer import (  # noqa: E402
    _SENTINEL_RE,
    enforce_build_label_footer,
)


def _mint_empty_footer_docx(path: Path) -> None:
    """Create a synthetic .docx with an empty default footer.

    Mirrors the Build 47 production artifact shape: every section has a
    Footer-styled paragraph with NO build-label run.  python-docx
    creates the empty styled paragraph as soon as we touch
    ``section.footer.paragraphs`` so we don't even need to write to it.
    """
    doc = docx.Document()
    doc.add_heading("Synthetic Round 75 self-test document", level=1)
    doc.add_paragraph(
        "This .docx is generated by the R75/Phase 5 enforcer smoke test. "
        "Its purpose is to verify _r74_footer_enforcer.enforce_build_label_footer "
        "actually injects the build-label run into word/footer1.xml on a doc "
        "that ships with an empty footer (the Build 47 production shape)."
    )
    # Touch the footer paragraph to force python-docx to instantiate
    # word/footer1.xml in the zip.  We DO NOT write any text to it --
    # mirrors the Build 47 artifact bug.
    section = doc.sections[0]
    _ = section.footer.paragraphs[0]
    doc.save(str(path))


def _read_footer1_xml(docx_path: Path) -> bytes:
    """Read ``word/footer1.xml`` from the docx zip.  Returns empty bytes when missing."""
    with zipfile.ZipFile(docx_path, mode="r") as zf:
        names = zf.namelist()
        if "word/footer1.xml" not in names:
            return b""
        return zf.read("word/footer1.xml")


def test_enforcer_injects_build_label_into_empty_footer():
    """The minted empty-footer .docx must carry the build-label
    sentinel in ``word/footer1.xml`` AFTER ``enforce_build_label_footer``
    runs against it."""
    with TemporaryDirectory() as tmpdir:
        target = Path(tmpdir) / "synthetic_empty_footer.docx"
        _mint_empty_footer_docx(target)

        # Pre-condition: the freshly-minted doc MUST NOT carry the sentinel.
        before = _read_footer1_xml(target)
        assert _SENTINEL_RE.search(before) is None, (
            "R75/Phase 5 fixture broken: the synthetic empty-footer "
            "doc unexpectedly already carries the build-label sentinel; "
            "the test cannot verify the enforcer's first-run behaviour."
        )

        # Run the enforcer.
        result = enforce_build_label_footer(target)
        assert result["injected"] is True, (
            f"R75/Phase 5 SMOKE FAIL: enforcer reported injected=False "
            f"on a synthetic empty-footer doc.  Result: {result!r}.  "
            f"This means the enforcer is NOT working in production -- "
            f"if Build 49 ships with this state the operator's reports "
            f"will continue to have empty footers."
        )
        assert "word/footer1.xml" in result["footer_parts_replaced"], (
            f"R75/Phase 5: enforcer reported injected=True but "
            f"footer_parts_replaced does not list word/footer1.xml: "
            f"{result!r}"
        )

        # Post-condition: the sentinel MUST appear in word/footer1.xml.
        after = _read_footer1_xml(target)
        assert _SENTINEL_RE.search(after) is not None, (
            "R75/Phase 5 SMOKE FAIL: enforcer claimed injected=True "
            "but word/footer1.xml does not contain the AdoptIQ vN "
            "sentinel after the rewrite.  Got footer XML:\n"
            f"{after.decode('utf-8', errors='replace')[:500]}"
        )

        # Idempotency: running the enforcer a second time must be a no-op.
        rerun = enforce_build_label_footer(target)
        assert rerun["injected"] is False, (
            f"R75/Phase 5: enforcer is NOT idempotent -- second run "
            f"reported injected=True (should be False with reason "
            f"'already stamped').  Result: {rerun!r}"
        )
        assert rerun["reason"] == "already stamped", rerun


def test_enforcer_label_carries_current_build_number():
    """The injected footer label must carry the CURRENT
    ``ADOPTIQ_BUILD`` from ``config.py`` so a stale-binary trap (the
    exact Build 47 trap that R75 closes) cannot recur silently in
    Build 49."""
    from config import ADOPTIQ_BUILD, ADOPTIQ_VERSION  # noqa: PLC0415

    with TemporaryDirectory() as tmpdir:
        target = Path(tmpdir) / "synthetic_for_build_check.docx"
        _mint_empty_footer_docx(target)
        result = enforce_build_label_footer(target)
        assert result["injected"] is True, result

        after = _read_footer1_xml(target)
        # Both the version AND build numbers must appear in the footer.
        assert ADOPTIQ_VERSION.encode("utf-8") in after, (
            f"R75/Phase 5: footer XML missing current ADOPTIQ_VERSION "
            f"({ADOPTIQ_VERSION}). Got:\n"
            f"{after.decode('utf-8', errors='replace')[:500]}"
        )
        assert ADOPTIQ_BUILD.encode("utf-8") in after, (
            f"R75/Phase 5: footer XML missing current ADOPTIQ_BUILD "
            f"({ADOPTIQ_BUILD}) -- a stale-binary trap could go "
            f"undetected. Got:\n"
            f"{after.decode('utf-8', errors='replace')[:500]}"
        )


def test_enforcer_handles_nonexistent_path_gracefully():
    """The enforcer MUST never raise -- a missing file returns a
    structured diag dict so the writer's completion path is never
    bricked."""
    result = enforce_build_label_footer("/tmp/this_file_definitely_does_not_exist_r75.docx")
    assert result["injected"] is False
    assert "file not found" in result["reason"]
