"""Round 66 / Pass 1 (B3) -- ``count_open_action_plans`` legacy XLSX backup detection.

R65/C-2 added the ``_adoptiq_provenance_row`` marker column to the
Comprehensive XLSX's ``Action_Plans`` sheet so a single explanatory
"EMPTY" row could ship without inflating the ``Action plans (open)``
KPI to 1. ``canonical_metrics.count_open_action_plans`` recognises this
marker column and skips marker rows.

But: workbooks generated by Build N where N < 38 carry the provenance
row WITHOUT the marker column (the column was added in R65). An
operator re-running ``count_open_action_plans`` against an archived
workbook (QA re-render, smoke harness, ad-hoc analysis) would read the
open-count as 1 instead of the truthful 0.

R66/B3 adds a backup heuristic: when the marker column is absent but
the row carries ``AdoptIQ_Status == 'EMPTY'`` (the public-facing
sentinel string preserved across builds), treat it as a provenance
row and skip it. The match is case-insensitive + whitespace-tolerant.

Round 66 / Pass 1.  Made-with: Cursor.
"""

from __future__ import annotations

import pandas as pd

from canonical_metrics import count_open_action_plans


# ---------------------------------------------------------------------------
# B3 — legacy fallback: ``AdoptIQ_Status == 'EMPTY'`` without marker column
# ---------------------------------------------------------------------------


def test_legacy_provenance_row_without_marker_column_recognized_via_status():
    """Pre-R65 export shape: provenance row carries ``AdoptIQ_Status='EMPTY'`` only.

    The marker column ``_adoptiq_provenance_row`` is absent (column
    didn't exist in older builds). The fallback heuristic must
    recognise the row by ``AdoptIQ_Status='EMPTY'`` and skip it,
    yielding open-count=0 not 1.
    """
    ap_df = pd.DataFrame([
        {
            "AdoptIQ_Status": "EMPTY",
            "AdoptIQ_Source": "CSConsole+Snowflake",
            "STATUS_C": None,
        }
    ])
    # Marker column intentionally absent (pre-R65 export shape).
    assert "_adoptiq_provenance_row" not in ap_df.columns

    count = count_open_action_plans(None, ap_df)
    assert count == 0, (
        f"legacy provenance row (AdoptIQ_Status='EMPTY' without marker "
        f"column) must be skipped from open-count; got {count}"
    )


def test_legacy_provenance_row_status_case_insensitive():
    """``AdoptIQ_Status`` matches case-insensitively (Empty / EMPTY / empty)."""
    for variant in ("EMPTY", "empty", "Empty", " Empty ", "  EMPTY  "):
        ap_df = pd.DataFrame([
            {"AdoptIQ_Status": variant, "STATUS_C": None}
        ])
        count = count_open_action_plans(None, ap_df)
        assert count == 0, (
            f"variant {variant!r} should be recognised as legacy "
            f"provenance row; got open count {count}"
        )


def test_legacy_provenance_row_keeps_real_rows():
    """A mix of legacy provenance + real rows: count only the real OPEN ones.

    Mixed shape (unusual but possible if a downstream step appended
    real rows on top of an EMPTY provenance row): the helper should
    skip the provenance row AND count the real rows correctly.
    """
    ap_df = pd.DataFrame([
        {"AdoptIQ_Status": "EMPTY", "STATUS_C": None},
        {"AdoptIQ_Status": "Open", "STATUS_C": "Open"},
        {"AdoptIQ_Status": "Open", "STATUS_C": "Completed - Successful"},
        {"AdoptIQ_Status": "Open", "STATUS_C": "Open"},
    ])
    count = count_open_action_plans(None, ap_df)
    # Provenance row skipped; 2 of the 3 real rows are open.
    assert count == 2, count


def test_marker_column_takes_precedence_over_legacy_heuristic():
    """When both marker column AND legacy status are present, marker wins.

    The marker column is the canonical R65 contract. The legacy
    heuristic is a back-compat fallback for workbooks that pre-date
    the marker. A workbook that has BOTH columns present (forward-
    compat / migration scenario) should follow the marker column's
    boolean value.
    """
    ap_df = pd.DataFrame([
        # Marker says NOT a provenance row, but status says EMPTY.
        # The marker (canonical) wins -- the row counts as a real AP.
        {"_adoptiq_provenance_row": False, "AdoptIQ_Status": "EMPTY", "STATUS_C": "Open"},
    ])
    count = count_open_action_plans(None, ap_df)
    # Marker column takes precedence -> the row is real -> count=1.
    assert count == 1, count


def test_legacy_status_empty_with_no_marker_column_then_truly_empty_returns_0():
    """Single provenance-style row only -> count must be 0 (not 1)."""
    ap_df = pd.DataFrame([
        {"AdoptIQ_Status": "EMPTY", "AdoptIQ_Source": "CSConsole+Snowflake"}
    ])
    assert count_open_action_plans(None, ap_df) == 0


def test_unrelated_status_value_in_legacy_column_does_not_skip_row():
    """A real AP row that happens to have an ``AdoptIQ_Status`` of
    something OTHER than ``EMPTY`` is NOT treated as a provenance row.

    Edge case: some legacy workbooks may carry ``AdoptIQ_Status`` as
    a normal data column with values like ``"REVIEWED"`` or
    ``"PARTIAL"``. Only the literal sentinel ``"EMPTY"`` triggers
    the skip.
    """
    ap_df = pd.DataFrame([
        {"AdoptIQ_Status": "REVIEWED", "STATUS_C": "Open"},
        {"AdoptIQ_Status": "PARTIAL", "STATUS_C": "Open"},
    ])
    # Both rows are open APs, neither is a provenance row.
    assert count_open_action_plans(None, ap_df) == 2


# ---------------------------------------------------------------------------
# B3 — back-compat: R65 marker column path still wins when present
# ---------------------------------------------------------------------------


def test_r65_marker_column_path_unchanged_with_b3_in_place():
    """The R65/C-2 marker-column path must continue to work unchanged."""
    ap_df = pd.DataFrame([
        {"_adoptiq_provenance_row": True, "AdoptIQ_Status": "EMPTY", "STATUS_C": None},
    ])
    assert count_open_action_plans(None, ap_df) == 0


def test_r65_marker_column_with_real_rows_still_counts_correctly():
    """Marker column tags only the provenance row; real OPEN rows count."""
    ap_df = pd.DataFrame([
        {"_adoptiq_provenance_row": True, "AdoptIQ_Status": "EMPTY", "STATUS_C": None},
        {"_adoptiq_provenance_row": False, "AdoptIQ_Status": None, "STATUS_C": "Open"},
        {"_adoptiq_provenance_row": False, "AdoptIQ_Status": None, "STATUS_C": "Completed - Successful"},
    ])
    # Provenance skipped; 1 OPEN of the remaining 2.
    assert count_open_action_plans(None, ap_df) == 1
